TravelCat/Models/spot.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelCat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spot
    {
        public string spot_id { get; set; }
        public string spot_title { get; set; }
        public string spot_tel { get; set; }
        public string spot_intro { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string addition_note { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string address_detail { get; set; }
        public string open_time { get; set; }
        public string ticket_info { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string travelling_info { get; set; }
        public bool page_status { get; set; }
    }
}

TravelCat/Controllers/SpotsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelCat.Models;
using TravelCat.ViewModels;
using X.PagedList;
using System.IO;

namespace TravelCat.Controllers
{
    [LoginCheck]
    public class SpotsController : Controller
    {
        // GET: Spot
        dbTravelCat db = new dbTravelCat();
        int pageSize = 10;


        public ActionResult Index(string id = null, int page = 1)
        {
            ViewBag.id = id;
            Session["pg"]=page;
            //int pageNumber = (page ?? 1);

            if (!String.IsNullOrEmpty(id))
            {
                var search = db.spot.Where(s => s.spot_id.Contains(id) || s.spot_title.Contains(id)
               || s.city.Contains(id) || s.district.Contains(id));
                return View(search.OrderBy(m => m.spot_id).ToPagedList(page, pageSize));
            }
            else
            {
                var data = db.spot.OrderBy(m => m.spot_id);
                return View(data.ToPagedList(page, pageSize));
            }
        }


        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(spot spot, HttpPostedFileBase[] tourism_photo)
        {
            //表單內容
            string act_id = db.Database.SqlQuery<string>("Select dbo.GetspotId()").FirstOrDefault();
            spot.spot_id = act_id;
            spot.update_date = DateTime.Now;
            spot.page_status = false;

            //圖片
            string fileName = "";
            for (int i = 0; i < tourism_photo.Length; i++)
            {
                HttpPostedFileBase f = tourism_photo[i];
                if (f != null)
                {
                    if (f.ContentLength > 0)
                    {
                        string t = tourism_photo[i].FileName;
                        fileName = spot.spot_id + "_" +DateTime.Now.ToString().Replace("/", "").Replace(":", "").Replace(" ", "") + (i + 1).ToString() + Path.GetExtension(t);
                        f.SaveAs(Server.MapPath("~/images/spot/" + fileName));
                        tourism_photo tp = new tourism_photo();
                        tp.tourism_photo1 = fileName;
                        tp.tourism_id = spot.spot_id;
                        db.tourism_photo.Add(tp);
                    }
                }
            }
            db.spot.Add(spot);
            db.SaveChanges();
            
            


            return RedirectToAction("Index",new { page=Session["pg"] });
        }

        public ActionResult Delete(string Id)
        {
            var product = db.spot.Where(m => m.spot_id == Id).FirstOrDefault();
            db.spot.Remove(product);
            db.SaveChanges();

            var photos = db.tourism_photo.Where(m => m.tourism_id == Id).ToList();
            for (int i = 0; i < photos.Count; i++)
            {
                string fileName = photos[i].tourism_photo1;
                if (fileName != "")
                {
                    System.IO.File.Delete(Server.MapPath("~/images/spot/" + fileName));
                }
                db.tourism_photo.Remove(photos[i]);
                db.SaveChanges();
            }
            return RedirectToAction("Index",new { page=Session["pg"] });
        }
        public ActionResult Edit(string id)
        {
            SpotPhotoViewModel model = new SpotPhotoViewModel()
            {
                spot = db.spot.Where(m => m.spot_id == id).FirstOrDefault(),

                spot_photos = db.tourism_photo.Where(m => m.tourism_id == id).ToList(),

            };
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(string id, SpotPhotoViewModel spotPhotoViewModel, HttpPostedFileBase[] tourism_photo, String oldImg)
        {

            spotPhotoViewModel.spot.update_date = DateTime.Now;
            db.Entry(spotPhotoViewModel.spot).State = EntityState.Modified;
            db.SaveChanges();

            //圖片
            string fileName = "";
            var tp1 = db.tourism_photo.Where(m => m.tourism_id == id).ToList();

            for (int i = 0; i < 3; i++)
            {
                if (tourism_photo[i] != null)
                {

                    //如果有新增檔案到input
                    if (tourism_photo[i].ContentLength > 0)
                    {
                        //改名
                        string t = tourism_photo[i].FileName;
                        fileName = spotPhotoViewModel.spot.spot_id + "_" + DateTime.Now.ToString().Replace("/", "").Replace(":", "").Replace(" ", "") + (i + 1).ToString() + Path.GetExtension(t);
                        if (i < tp1.Count)  //如果原有紀錄
                        {
                            //刪掉原檔案
                            System.IO.File.Delete(Server.MapPath("~/images/spot/" + tp1[i].tourism_photo1));
                            tourism_photo[i].SaveAs(Server.MapPath("~/images/spot/" + fileName));      //將檔案存到該資料夾
                            //改掉資料庫檔案
                            tp1[i].tourism_photo1 = fileName;
                        }
                        else //如果原本沒有
                        {
                            tourism_photo tp = new tourism_photo();
                            tp.tourism_photo1 = fileName;
                            tourism_photo[i].SaveAs(Server.MapPath("~/images/spot/" + fileName));
                            tp.tourism_id = spotPhotoViewModel.spot.spot_id;
                            db.tourism_photo.Add(tp);
                        }
                    }
                    //else 
                    //{

                    //}
                }
                //else //if(String.IsNullOrEmpty(oldImg))
                //{
                //    tourism_photo tp = new tourism_photo();
                //    tp.tourism_photo1 = fileName;
                //    tp.tourism_id = spotPhotoViewModel.spot.spot_id;
                //    db.tourism_photo.Add(tp);
                //}

            }
            db.SaveChanges();
            return RedirectToAction("Index",new { page = Session["pg"] });

        }
    }
}

TravelCat/Views/Spots/Create.cshtml
@model TravelCat.ViewModels.SpotPhotoViewModel

@{
    ViewBag.Title = "新增景點";
}

<link href="~/Content/back-end-Create.css" rel="stylesheet" />

<h2 class="ml-3 mt-3 text-danger text-center">新增景點</h2>


<form action="/Spots/Create" method="post" enctype="multipart/form-data">

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.HiddenFor(model=>model.spot.page_status)
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <!--名稱-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_title, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.spot_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.spot_title, "", new { @class = "text-danger" })

            </div>
        </div>

        <!--電話-->
        <div class="row">
            <div class=" co col-6">
                @Html.LabelFor(model => model.spot.spot_tel, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.spot_tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.spot_tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--經度-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.longitude, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--緯度-->
        <div class="row">
            <div class=" co col-6">
                @Html.LabelFor(model => model.spot.latitude, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--城市-->
        <div class="row ">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.city, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.city, "", new { @class = "text-danger" })
            </div>
        </div>


        <!--行政區-->
        <div class="row">
            <div class=" co col-6">
                @Html.LabelFor(model => model.spot.district, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.district, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.spot.district, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--街道地址-->
        <div class="row ">

            <div class="co col-6">
                @Html.LabelFor(model => model.spot.address_detail, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.address_detail, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.spot.address_detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--營業時間-->
        <div class="row ">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.open_time, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.open_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.open_time, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--門票資訊-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.ticket_info, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.ticket_info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.ticket_info, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--簡介-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_intro, htmlAttributes: new { @class = "txt" })
                @Html.TextAreaFor(model => model.spot.spot_intro, new { @class = "form-control", rows = "5" })
                @Html.ValidationMessageFor(model => model.spot.spot_intro, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--備註-->
        <div class="row ">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.addition_note, htmlAttributes: new { @class = "txt" })
                @Html.TextAreaFor(model => model.spot.addition_note, new { @class = "form-control", rows = "5" })
                @Html.ValidationMessageFor(model => model.spot.addition_note, "", new { @class = "text-danger" })

            </div>
        </div>

        <!--新增圖片-->
        <div class=" row">

            <div class="co col-6">
                @Html.LabelFor(model => model.spot_photos[0].tourism_photo1, htmlAttributes: new { @class = "txt" })
                <input id="tourism_photo" name="tourism_photo" type="file" class="form-control" />
                @Html.ValidationMessageFor(model => model.spot_photos[0].tourism_photo1, "", new { @class = "text-danger" })
                <input id="tourism_photo" name="tourism_photo" type="file" class="form-control" />
                @Html.ValidationMessageFor(model => model.spot_photos[1].tourism_photo1, "", new { @class = "text-danger" })
                <input id="tourism_photo" name="tourism_photo" type="file" class="form-control" />
                @Html.ValidationMessageFor(model => model.spot_photos[2].tourism_photo1, "", new { @class = "text-danger" })

            </div>
        </div>

        <!--下方按鈕-->
        <div class="row text-center m-3">
            <div class="col-1">
                <input type="submit" value="新增" class="btn btn-primary" />

            </div>
            <div class="col-2">
                @Html.ActionLink("回到景點列表", "Index", new { page = Session["pg"] }, new { @class = "btn btn-primary" })

            </div>
        </div>
    </div>
</form>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

TravelCat/Views/Spots/Edit.cshtml
@model TravelCat.ViewModels.SpotPhotoViewModel

@{
    ViewBag.Title = "修改景點";
}

<link href="~/Content/back-end-Create.css" rel="stylesheet" />
<h2 class="ml-3 mt-3 text-danger text-center">修改景點</h2>

<form method="post" action="@Url.Action("Edit")" enctype="multipart/form-data">

    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.spot.spot_id)

        <!--頁面狀態-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.page_status, htmlAttributes: new { @class = "txt" })
                <select id="Select1" name="spot.page_status" class="form-control">
                    <option value="False">顯示</option>
                    <option value="True">隱藏</option>
                </select>
                @Html.ValidationMessageFor(model => model.spot.page_status, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--編號-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <input id="spot_id" name="spot_id" type="text" readonly="readonly" value="@Model.spot.spot_id" class="form-control" />
            </div>
        </div>

        <!--編號-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_id, htmlAttributes: new { @class = "txt" })
                <input id="spot_id" name="spot_id" type="text" readonly="readonly" value="@Model.spot.spot_id" class="form-control" />
            </div>
        </div>

        <!--名稱-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_title, htmlAttributes: new { @class = "txt" })

                @Html.EditorFor(model => model.spot.spot_title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.spot_title, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--電話-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_tel, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.spot_tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.spot_tel, "", new { @class = "text-danger" })
            </div>
        </div>


        <!--經度-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.longitude, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.longitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--緯度-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.latitude, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.latitude, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--城市-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.city, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.city, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--行政區-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.district, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.district, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.district, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--詳細地址-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.address_detail, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.address_detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.address_detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--營業時間-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.open_time, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.open_time, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.open_time, "", new { @class = "text-danger" })
            </div>
        </div>

        <!--門票資訊-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.ticket_info, htmlAttributes: new { @class = "txt" })
                @Html.EditorFor(model => model.spot.ticket_info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.spot.ticket_info, "", new { @class = "text-danger" })
            </div>
        </div>


        <!--簡介-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.spot_intro, htmlAttributes: new { @class = "txt" })
                @Html.TextAreaFor(model => model.spot.spot_intro, new { @class = "form-control", rows = "5" })
                @Html.ValidationMessageFor(model => model.spot.spot_intro, "", new { @class = "text-danger" })

            </div>
        </div>

        <!--備註-->
        <div class="row">
            <div class="co col-6">
                @Html.LabelFor(model => model.spot.addition_note, htmlAttributes: new { @class = "txt" })
                @Html.TextAreaFor(model => model.spot.addition_note, new { @class = "form-control", rows = "5" })
                @Html.ValidationMessageFor(model => model.spot.addition_note, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="row">
            <div class="co col-6">
                <label class="">圖片</label>

                <div class="row">
                    @{ var photo = Model.spot_photos.Where(m => m.tourism_id == Model.spot.spot_id).ToList();
                        for (int i = 0; i < 3; i++)
                        {
                            <div class="col-md-4">
                                @if (i > photo.Count - 1)
                                {
                                    <h3>no image</h3>
                                }
                                else
                                {
                                    <img src="/images/spot/@photo[i].tourism_photo1" width="150" />
                                    <input id="oldImg" name="oldImg" type="text" value="@photo[i].tourism_photo1" />
                                }
                                <input id="tourism_photo" name="tourism_photo" type="file" class="form-control" />
                                @Html.ValidationMessageFor(model => model.spot_photos[i].tourism_photo1, "", new { @class = "text-danger" })
                            </div>
                        }
                    }
                </div>

            </div>
        </div>

        <!--下方按鈕-->
        <div class="row text-center m-3">
            <div class="col-1">
                <input type="submit" value="儲存" class="btn btn-primary" />
            </div>
            <div class="col-1">
                @Html.ActionLink("刪除", "Delete", new { id = Model.spot.spot_id }, new { @class = "btn btn-danger", onclick = "return confirm('確定不後悔?')" })
            </div>
            <div class="col-2">
                @Html.ActionLink("回到景點列表", "Index", new { page = Session["pg"] }, new { @class = "btn btn-primary" })
            </div>

        </div>
    </div>
</form>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script>
        $('#Select1 option[value=@Model.spot.page_status]').attr('selected', 'selected');
    </script>

}

TravelCat/Views/Spots/Index.cshtml
@using X.PagedList.Mvc
@using X.PagedList
@using X.PagedList.Mvc.Common

@model IPagedList<TravelCat.Models.spot>
@{

    ViewBag.Title = "景點列表";
}

<link href="~/Content/back-end-index.css" rel="stylesheet" />
<h2 class="mt-3 text-center">景點</h2>
<div class="header ml-3">
    @Html.ActionLink("新增景點", "Create", "Spots", null, new { @class = "btn btn-secondary" })
    <div class="search">

        @*@Html.TextBox("id", "", new { @class = " border", @placeholder = "編號,名稱,城市,行政區" })

            @Html.ActionLink("查詢", "contentQuery", new { id = "id" }, new{@class="btn btn-default"})*@
        <form action="@Url.Action("Index","Spots")" method="get">
            @Html.TextBox("id", "", new { @class = " border", @placeholder = "編號,名稱,城市,行政區" })
            <input class="btn btn-secondary" type="submit" value="查詢" />
        </form>

    </div>

</div>



<table class="table">
    <tr class="row ">
        <th class="col-1"></th>
        <th class="col-1">
            @Html.DisplayNameFor(model => model.First().spot_id)
        </th>
        <th class="col-2 text-truncate">
            @Html.DisplayNameFor(model => model.First().spot_title)
        </th>
        <th class="col-2 text-truncate">
            @Html.DisplayNameFor(model => model.First().spot_tel)
        </th>
        <th class="col-1">
            @Html.DisplayNameFor(model => model.First().city)
        </th>
        <th class="col-1">
            @Html.DisplayNameFor(model => model.First().district)
        </th>
        <th class="col-1 text-truncate">
            @Html.DisplayNameFor(model => model.First().open_time)
        </th>
        <th class="col-2">
            @Html.DisplayNameFor(model => model.First().update_date)
        </th>
        <th class="col-1">
            @Html.DisplayNameFor(model => model.First().page_status)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="row">
            <td class="col-1 text-center">
                @Html.ActionLink("檢視/修改", "Edit", new { id = item.spot_id }, new { @class = "btn btn-sm btn-outline-primary" })
            </td>
            <td class="col-1">
                @Html.DisplayFor(modelItem => item.spot_id)
            </td>
            <td class="col-2 text-truncate">
                @Html.DisplayFor(modelItem => item.spot_title)
            </td>
            <td class="col-2 text-truncate">
                @Html.DisplayFor(modelItem => item.spot_tel)
            </td>
            <td class="col-1">
                @Html.DisplayFor(modelItem => item.city)
            </td>
            <td class="col-1">
                @Html.DisplayFor(modelItem => item.district)
            </td>
            <td class="col-1 text-truncate">
                @Html.DisplayFor(modelItem => item.open_time)
            </td>
            <td class="col-2">
                @Html.DisplayFor(modelItem => item.update_date)
            </td>
            <td class="col-1">
                @if (item.page_status == false)
                {
                    <span class="badge badge-success">顯示</span>
                }
                else
                {
                    <span class="badge badge-danger">隱藏</span>
                }
            </td>
        </tr>
    }

</table>

<!--分頁-->
<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, id = ViewBag.id }),
                  new PagedListRenderOptions
                  {
                      ContainerDivClasses = new[] { "" },
                           LiElementClasses = new[] { "page-item" },
                           PageClasses = new[] { "page-link" },
                  })
</div>